[package]
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
name = "akuma"
version = "0.1.0"
autobenches = false

[dev-dependencies]
criterion = "0.3.3"

[dependencies]
derive_is_enum_variant = "0.1.1"
lazy_static = "1.4.0"
regex = "1.4.2"
flame = { version = "0.2.2", optional = true }
flamer = { version = "0.4.0", optional = true }
rustyline = "6.3.0"
derivative = "2.1.1"

[dependencies.string-interner]
git = "https://git.hunterpraska.com/hunter/incarnation"

[dependencies.vm]
path = "vm"

[features]
default = []
profile = ["flame", "flamer"]

[[bench]]
name = "fibonacci"
harness = false

[[bench]]
name = "count"
harness = false
