[package]
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
name = "akuma"
version = "0.1.0"

[dependencies]
derive_is_enum_variant = "0.1.1"
lazy_static = "0.2.11"
maplit = "1.0.0"
num = "0.1.40"
regex = "0.2.2"

[dependencies.flame]
optional = true
version = "0.2.0"

[dependencies.flamer]
optional = true
version = "0.1.4"

[features]
default = []
flame_it = ["flame", "flamer"]
