[package]
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
name = "akuma"
version = "0.1.0"

[dev-dependencies]
criterion = "0.2"

[dependencies]
derive_is_enum_variant = "0.1.1"
lazy_static = "1.0.1"
regex = "1.0.0"
flame = { version = "0.2.2", optional = true }
#flamer = { version = "0.2.5", optional = true }
flamer = { git = "https://github.com/llogiq/flamer", optional = true }

[dependencies.vm]
path = "vm"

[features]
default = []
profile = ["flame", "flamer"]

[profile.release]
debug = true
lto = false

[[bench]]
name = "fibonacci"
harness = false
