[package]
name = "vm"
version = "0.1.0"
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]

[dependencies]
string-interner = "0.7.0"

[dev-dependencies]
criterion = "0.2.5"

[[bench]]
name = "basic"
harness = false
